[package]

name = "tnexus"
version = "0.0.2"
authors = [ "Andrey Petrov <andreypetrov@yahoo.com>" ]

[[bin]]

name = "tnexus"

[dependencies]
mio = "0.5"
bytes  = "0.3.0"
toml = "0.1.25"
openssl = "0.7.4"
hyper = "0.8.0"
rustc-serialize = "0.3"
env_logger = "0.3.1"
log = "0.3.3"
